name: "OpenTelemetry-Matlab"
on: workflow_dispatch
jobs:
    build-and-run-tests:
        runs-on: ubuntu-latest
        env:
            OPENTELEMETRY_CPP_INSTALL: "/home/runner/work/otel_cpp_install"
            OPENTELEMETRY_MATLAB_INSTALL: "/home/runner/work/otel_matlab_install"
            OPENTELEMETRY_COLLECTOR_INSTALL: "../../otelcol"
        steps:
            - name: Download OpenTelemetry-Matlab source
              uses: actions/checkout@v3
              with: 
                path: opentelemetry-matlab
            - name: Download OpenTelemetry-cpp source
              uses: actions/checkout@v3
              with: 
                repository: open-telemetry/opentelemetry-cpp
                path: opentelemetry-cpp
                ref: v1.8.3
            - name: Download vcpkg
              uses: actions/checkout@v3
              with: 
                repository: microsoft/vcpkg
                path: vcpkg
            - name: Install MATLAB
              uses: matlab-actions/setup-matlab@v1
            - name: Install vcpkg packages
              run:
                  cd vcpkg
                  ./bootstrap-vcpkg.sh
                  ./vcpkg install abseil c-ares curl grpc nlohmann-json openssl protobuf re2 upb zlib gtest benchmark
            - name: Download OpenTelemetry Collector binary
              run:
                  mkdir otelcol && cd otelcol
                  wget https://github.com/open-telemetry/opentelemetry-collector-releases/releases/download/v0.75.0/otelcol_0.75.0_linux_amd64.tar.gz
                  tar -xzf otelcol_0.75.0_linux_amd64.tar.gz
            - name: Build OpenTelemetry-cpp
              run:
                  cd opentelemetry-cpp
                  cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DCMAKE_CXX_STANDARD=20 -DWITH_OTLP_HTTP=TRUE -DWITH_OTLP_GRPC=TRUE -DOPENTELEMETRY_INSTALL=ON -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake
                  cmake --build build --config Release --target all
                  cmake --install build --prefix ${{ env.OPENTELEMETRY_CPP_INSTALL }}
            - name: Build OpenTelemetry-Matlab
              run:
                  cd opentelemetry-matlab
                  cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${{ env.OPENTELEMETRY_MATLAB_INSTALL }} -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_PREFIX_PATH=${{ env.OPENTELEMETRY_CPP_INSTALL }}/lib/cmake/opentelemetry-cpp
                  cmake --build build --config Release --target install
            - name: Run tests
              uses: matlab-actions/run-command@v1
              with:
                  command: addpath("${{ env.OPENTELEMETRY_MATLAB_INSTALL }}"), cd(fullfile("opentelemetry-matlab","test")), runtests("."); 
